server.port: 8080
spring.application.name: gateway-service

spring:
  cloud:
    gateway:
      routes:
        - id: user_route
          uri: lb://user-service
          predicates:
            - Path=/api/v1/user/**
            - Method=POST,GET,PUT,OPTION
          filters:
            - RewritePath=/api/v1/user/(?<remaining>.*), /user/${remaining}

        - id: product_route
          uri: lb://product-service
          predicates:
            - Path=/api/v1/product/**
            - Method=POST,GET,OPTION
          filters:
            - RewritePath=/api/v1/product/(?<remaining>.*), /product/${remaining}

        - id: order_route
          uri: lb://order-service
          predicates:
            - Path=/api/v1/order/**
            - Method=POST,GET,PUT,OPTION
          filters:
            - RewritePath=/api/v1/order/(?<remaining>.*), /order/${remaining}

        - id: pay_route
          uri: lb://pay-service
          predicates:
            - Path=/api/v1/payment/**
            - Method=POST,GET,PUT,OPTION
          filters:
            - RewritePath=/api/v1/payment/(?<remaining>.*), /payment/${remaining}

        - id: inventory_route
          uri: lb://inventory-service
          predicates:
            - Path=/api/v1/inventory/**
            - Method=POST,GET,PUT,OPTION
          filters:
            - RewritePath=/api/v1/inventory/(?<remaining>.*), /inventory/${remaining}

eureka:
  instance:
    hostname: ${EUREKA_INSTANCE_HOSTNAME}
  client:
    service-url:
        defaultZone: http://${EUREKA_SERVER_HOSTNAME}:${EUREKA_SERVER_PORT}/eureka/
    registerWithEureka: true
    fetchRegistry: true

    rest-template-timeout:
      connect-timeout: 5000
      connect-request-timeout: 8000
      socket-timeout: 10000