server.port: 8102
spring.application.name: order-service

spring:
  profiles.include:
    - aws

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7000/eureka/
    registerWithEureka: true
    fetchRegistry: true

