server.port: 8102
spring.application.name: order-service

spring:
  datasource:
    url: jdbc:h2:mem:order-dev;DB_CLOSE_DELAY=-1
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
  h2:
    console:
      enabled: true
      path: /h2-console
  sql:
    init:
      schema-locations: classpath:sql/schema-h2.sql

eureka:
  instance:
    hostname: ${EUREKA_INSTANCE_HOSTNAME}
  client:
    service-url:
      defaultZone: http://${EUREKA_SERVER_HOSTNAME}:${EUREKA_SERVER_PORT}/eureka/
    registerWithEureka: true
    fetchRegistry: true


gateway.service.url: http://${GATEWAY_INSTANCE_HOSTNAME}:${GATEWAY_SERVER_PORT}
product.service.url: ${gateway.service.url}/api/v1/product
