server.port: 8101
spring.application.name: product-service

eureka:
  instance:
    hostname: ${EUREKA_INSTANCE_HOSTNAME}
  client:
    service-url:
      defaultZone: http://${EUREKA_SERVER_HOSTNAME}:${EUREKA_SERVER_PORT}/eureka/
    registerWithEureka: true
    fetchRegistry: true


gateway.service.url: http://${GATEWAY_INSTANCE_HOSTNAME:gateway-service}:${GATEWAY_SERVER_PORT:8080}
inventory.service.url: ${gateway.service.url}/api/v1/inventory
