server.port: 8101
spring.application.name: product-service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7000/eureka/
    registerWithEureka: true
    fetchRegistry: true


inventory.service.url: "http://localhost:8080/api/v1/inventory"
gateway.service.url: "http://localhost:8080"