server.port: 8101
spring.application.name: product-service

eureka:
  instance:
    hostname: ${EUREKA_INSTANCE_HOSTNAME}
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://${EUREKA_SERVER_HOSTNAME}:${EUREKA_SERVER_PORT}/eureka/
    registerWithEureka: true
    fetchRegistry: true


inventory.service.url: http://${INVENTORY_INSTANCE_HOSTNAME:inventory-service}:${INVENTORY_SERVER_PORT:8104}
