server.port: 8104
spring.application.name: inventory-service

eureka:
  instance:
    hostname: ${EUREKA_INSTANCE_HOSTNAME:inventory-service}
  client:
    service-url:
      defaultZone: http://${EUREKA_SERVER_HOSTNAME:eureka-service}:${EUREKA_SERVER_PORT:7000}/eureka/
    registerWithEureka: true
    fetchRegistry: true