server.port: 8104
spring.application.name: inventory-service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7000/eureka/
    registerWithEureka: true
    fetchRegistry: true

product.service.url: "http://localhost:8080/product"