server.port: 8103
spring.application.name: pay-service

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${mysql.endpoint}:${mysql.port}/${mysql.database-name}?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ${mysql.credentials.username}
    password: ${mysql.credentials.password}
  jpa:
    defer-datasource-initialization: true
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
  sql:
    init:
      schema-locations: classpath:sql/schema-mysql.sql

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7000/eureka/
    registerWithEureka: true
    fetchRegistry: true


product.service.url: "http://localhost:8080/api/v1/order"
gateway.service.url: "http://localhost:8080"